// AUTO-GENERATED by tools/generate.py — do not edit by hand.
window.DOJO_CHEATSHEET = [
  {
    "group": "Navigate",
    "cmd": "pwd",
    "what": "where am I"
  },
  {
    "group": "Navigate",
    "cmd": "cd - / cd ~ / cd ..",
    "what": "previous dir / home / parent"
  },
  {
    "group": "Navigate",
    "cmd": "ls -lath",
    "what": "long + hidden + by date + human sizes"
  },
  {
    "group": "Navigate",
    "cmd": "mkdir -p a/b/{c,d}",
    "what": "build a whole tree at once"
  },
  {
    "group": "Files",
    "cmd": "cp -r src dst",
    "what": "copy (dirs need -r)"
  },
  {
    "group": "Files",
    "cmd": "mv old new",
    "what": "move AND rename"
  },
  {
    "group": "Files",
    "cmd": "rm -r dir",
    "what": "delete, no trash — respect it"
  },
  {
    "group": "Files",
    "cmd": "ln -s target link",
    "what": "symbolic link (shortcut)"
  },
  {
    "group": "Files",
    "cmd": "file mystery",
    "what": "what kind of file is this?"
  },
  {
    "group": "Read",
    "cmd": "cat / less / head -n / tail -n",
    "what": "dump / page / first / last lines"
  },
  {
    "group": "Read",
    "cmd": "tail -f app.log",
    "what": "follow a log live (Ctrl+C quits)"
  },
  {
    "group": "Read",
    "cmd": "wc -l file",
    "what": "count lines"
  },
  {
    "group": "Vim",
    "cmd": "i · Esc · :wq · :q!",
    "what": "insert · normal · save+quit · quit no-save"
  },
  {
    "group": "Vim",
    "cmd": "dd yy p u",
    "what": "delete line, yank, paste, undo"
  },
  {
    "group": "Vim",
    "cmd": "/search  n  ·  :%s/a/b/g",
    "what": "search/next · replace everywhere"
  },
  {
    "group": "Vim",
    "cmd": "vimtutor",
    "what": "the 15-minute tutorial that saves a year of pain"
  },
  {
    "group": "Permissions",
    "cmd": "chmod u+x script.sh",
    "what": "add execute for the owner"
  },
  {
    "group": "Permissions",
    "cmd": "chmod 755 / 700 / 644 / 600",
    "what": "the four classics (r4 w2 x1)"
  },
  {
    "group": "Permissions",
    "cmd": "sudo chown user:group file",
    "what": "change owner and group"
  },
  {
    "group": "Permissions",
    "cmd": "umask 027",
    "what": "666-027=640 files, 777-027=750 dirs"
  },
  {
    "group": "Permissions",
    "cmd": "id",
    "what": "your uid, gid and groups"
  },
  {
    "group": "Pipes",
    "cmd": "cmd1 | cmd2",
    "what": "stdout of one becomes stdin of the next"
  },
  {
    "group": "Pipes",
    "cmd": "> >> 2> 2>&1",
    "what": "overwrite / append / errors only / all together"
  },
  {
    "group": "Pipes",
    "cmd": "sort | uniq -c | sort -rn",
    "what": "the frequency-table idiom"
  },
  {
    "group": "Pipes",
    "cmd": "tee file",
    "what": "show on screen AND save"
  },
  {
    "group": "Pipes",
    "cmd": "xargs cmd",
    "what": "turn stdin into arguments"
  },
  {
    "group": "Hunt",
    "cmd": "grep -rn 'pat' dir/",
    "what": "search everything, with line numbers"
  },
  {
    "group": "Hunt",
    "cmd": "grep -i / -v / -c",
    "what": "ignore case / invert / count"
  },
  {
    "group": "Hunt",
    "cmd": "find . -name '*.log'",
    "what": "find by name"
  },
  {
    "group": "Hunt",
    "cmd": "find . -type f -size +10M -mtime -7",
    "what": "by type, size, age"
  },
  {
    "group": "Transform",
    "cmd": "sed -i.bak 's/old/new/g' f",
    "what": "replace in place (portable, keeps .bak)"
  },
  {
    "group": "Transform",
    "cmd": "tr a-z A-Z < f",
    "what": "translate characters"
  },
  {
    "group": "Transform",
    "cmd": "awk '{print $2}'",
    "what": "print the 2nd column"
  },
  {
    "group": "Transform",
    "cmd": "awk -F: '{print $1}' /etc/passwd",
    "what": "custom field separator"
  },
  {
    "group": "Transform",
    "cmd": "cut -d, -f1,3",
    "what": "columns 1 and 3 of a CSV"
  },
  {
    "group": "Processes",
    "cmd": "ps aux | grep name",
    "what": "find a process"
  },
  {
    "group": "Processes",
    "cmd": "top / htop",
    "what": "live dashboard (F9 kills in htop)"
  },
  {
    "group": "Processes",
    "cmd": "kill PID / kill -9 PID",
    "what": "ask nicely (TERM) / force (KILL)"
  },
  {
    "group": "Processes",
    "cmd": "pkill -f 'pattern'",
    "what": "signal by name/pattern"
  },
  {
    "group": "Processes",
    "cmd": "cmd & · jobs · fg · bg · Ctrl+Z",
    "what": "background · list · front · resume · suspend"
  },
  {
    "group": "Processes",
    "cmd": "nohup cmd >log 2>&1 &",
    "what": "survive logout, capture output"
  },
  {
    "group": "Services",
    "cmd": "systemctl status svc",
    "what": "state + last log lines"
  },
  {
    "group": "Services",
    "cmd": "sudo systemctl restart/enable svc",
    "what": "restart / start on boot"
  },
  {
    "group": "Services",
    "cmd": "journalctl -u svc -n 50 -f",
    "what": "a service's logs (50, live)"
  },
  {
    "group": "Packages",
    "cmd": "sudo apt update && sudo apt upgrade",
    "what": "refresh catalog + upgrade installed"
  },
  {
    "group": "Packages",
    "cmd": "apt search / apt show pkg",
    "what": "find / inspect a package"
  },
  {
    "group": "Packages",
    "cmd": "dpkg -L pkg  /  dpkg -S path",
    "what": "what it installed / who owns a file"
  },
  {
    "group": "Packages",
    "cmd": "dnf … / pacman -S …",
    "what": "Fedora/RHEL … / Arch equivalents"
  },
  {
    "group": "Packages",
    "cmd": "which cmd",
    "what": "where the executable lives"
  },
  {
    "group": "Scripts",
    "cmd": "#!/usr/bin/env bash",
    "what": "shebang: who runs this file"
  },
  {
    "group": "Scripts",
    "cmd": "set -euo pipefail",
    "what": "strict mode: exit-on-error, no-unset, pipe-safe"
  },
  {
    "group": "Scripts",
    "cmd": "$1 $2 $# $? $@",
    "what": "args, count, last exit code, all args"
  },
  {
    "group": "Scripts",
    "cmd": "if [ -d \"$X\" ]; then … fi",
    "what": "test a dir (-f file, -e exists)"
  },
  {
    "group": "Scripts",
    "cmd": "for f in *.log; do … done",
    "what": "loop over files"
  },
  {
    "group": "Scripts",
    "cmd": "VAR=${1:-default}",
    "what": "argument with a default value"
  },
  {
    "group": "Cron",
    "cmd": "crontab -e  /  crontab -l",
    "what": "edit / list schedules"
  },
  {
    "group": "Cron",
    "cmd": "*/5 * * * * command",
    "what": "every 5 min (min h dom mon dow)"
  },
  {
    "group": "Network",
    "cmd": "ip a",
    "what": "interfaces and IPs"
  },
  {
    "group": "Network",
    "cmd": "ping -c 3 host",
    "what": "can I reach it?"
  },
  {
    "group": "Network",
    "cmd": "dig domain +short",
    "what": "does DNS resolve?"
  },
  {
    "group": "Network",
    "cmd": "curl -I url  /  curl -s url",
    "what": "headers / silent body"
  },
  {
    "group": "Network",
    "cmd": "ss -tlnp",
    "what": "listening ports + which process"
  },
  {
    "group": "Network",
    "cmd": "ssh-keygen -t ed25519",
    "what": "generate a key pair"
  },
  {
    "group": "Network",
    "cmd": "ssh user@host  /  scp f user@host:~/",
    "what": "remote shell / copy over ssh"
  },
  {
    "group": "Git & SSH",
    "cmd": "git init / add / commit -m",
    "what": "start a repo, stage, commit"
  },
  {
    "group": "Git & SSH",
    "cmd": "git checkout -- file",
    "what": "restore a file — your time machine"
  },
  {
    "group": "Git & SSH",
    "cmd": "cat ~/.ssh/id_ed25519.pub",
    "what": "the PUBLIC key (the one you share)"
  },
  {
    "group": "Git & SSH",
    "cmd": "ssh -T git@github.com",
    "what": "test your GitHub SSH auth"
  },
  {
    "group": "Disk",
    "cmd": "df -h",
    "what": "free space per filesystem"
  },
  {
    "group": "Disk",
    "cmd": "du -sh */ | sort -rh",
    "what": "what's taking the most space"
  },
  {
    "group": "Disk",
    "cmd": "ncdu",
    "what": "interactive disk explorer"
  },
  {
    "group": "Disk",
    "cmd": "tar -czf x.tgz dir / tar -xzf x.tgz",
    "what": "compress / extract (-tzf lists)"
  },
  {
    "group": "System",
    "cmd": "free -h / uname -a / cat /etc/os-release",
    "what": "RAM / kernel / distro"
  },
  {
    "group": "System",
    "cmd": "/etc  /var/log  /proc  /tmp",
    "what": "configs / logs / kernel x-ray / scratch"
  },
  {
    "group": "Env",
    "cmd": "export VAR=v ; echo $PATH",
    "what": "environment vars ; the command search path"
  },
  {
    "group": "Env",
    "cmd": "echo 'alias ll=\"ls -lah\"' >> ~/.bashrc && source ~/.bashrc",
    "what": "a permanent alias"
  },
  {
    "group": "Help",
    "cmd": "man cmd · cmd --help · tldr cmd",
    "what": "manual · summary · examples"
  },
  {
    "group": "WSL",
    "cmd": "wsl --install  (PowerShell as admin)",
    "what": "install WSL2 + Ubuntu in one command"
  },
  {
    "group": "WSL",
    "cmd": "/mnt/c",
    "what": "your Windows drive, seen from Linux"
  },
  {
    "group": "WSL",
    "cmd": "wsl --shutdown  (PowerShell)",
    "what": "restart the WSL engine"
  },
  {
    "group": "WSL",
    "cmd": "\\\\wsl$\\Ubuntu  (in Explorer)",
    "what": "your Linux files, seen from Windows"
  }
];
