// AUTO-GENERATED by tools/generate.py — do not edit by hand.
window.DOJO_EXTRAS = {
  "rules": [
    "Everything happens inside the repo. Never run a destructive command outside your dojo.",
    "Use `sudo` only when a mission tells you to — with sudo, Linux obeys even dumb orders.",
    "`rm` has no trash can: once it's deleted, it's gone. Respect it."
  ],
  "pact": [
    "Type everything by hand — no pasting. The memory goes to your fingers.",
    "Stuck? Reach for `man <cmd>` or `<cmd> --help` **before** any AI.",
    "Fumbling a command *is* the training. Every error is a rep."
  ],
  "katas": [
    "Without looking anything up: create a tree of 3 folders with one command, a file in each, and list it all with `ls -R`.",
    "Find every file in the repo modified in the last 24h (`find . -mtime -1`).",
    "Build a pipeline that counts how many unique words a text file has.",
    "In vim, write 5 lines, duplicate the last (`yy p`), replace a word everywhere (`:%s`) and save.",
    "Start a `sleep` in the background, find its PID with a pipeline, and kill it without typing the number by hand.",
    "Translate to octal and apply: a file only you can read/write, and the group can only read.",
    "Find the 3 largest folders under your home with `du` + `sort`.",
    "Serve a folder with `python3 -m http.server`, confirm the port with `ss -tlnp`, `curl` it, then take it down.",
    "Write a one-liner that appends the date and time to `diary.log` every time it runs.",
    "Find which package owns the `grep` command (`which` + your distro's package query).",
    "Create a new alias in your shell rc, reload it with `source`, and use it.",
    "Read the last 20 log lines of a service with `journalctl -u <service>` (on a systemd box).",
    "Generate 100 lines of fake log and extract only the ones containing ERROR into a file.",
    "Compress a folder with `tar -czf` and list its contents without extracting (`-tzf`).",
    "In `man find`, discover an option you've never used and try it.",
    "Write an `if` in a script that checks a folder exists and complains on stderr if it doesn't.",
    "Rank your most-used commands (`history` + `awk` + `sort` + `uniq`).",
    "Diagnose a host: find your IP, test DNS with a lookup, and grab a site's headers with `curl -I`.",
    "Suspend a process with Ctrl+Z, list it with `jobs`, send it to the background with `bg`, bring it back with `fg`.",
    "Read a permission string like `-rwxr-x---` out loud, then write its octal from memory."
  ],
  "trophies": [
    {
      "icon": "🐣",
      "title": "First Step",
      "desc": "Cleared your very first mission",
      "cond": {
        "type": "first"
      }
    },
    {
      "icon": "🌳",
      "title": "Gardener",
      "desc": "White Belt complete — the file tree",
      "cond": {
        "type": "belt",
        "n": 1
      }
    },
    {
      "icon": "📦",
      "title": "Wrangler",
      "desc": "Yellow Belt complete — cp/mv/rm/find",
      "cond": {
        "type": "belt",
        "n": 2
      }
    },
    {
      "icon": "🪠",
      "title": "Unix Plumber",
      "desc": "Orange Belt complete — pipes & text",
      "cond": {
        "type": "belt",
        "n": 3
      }
    },
    {
      "icon": "🔐",
      "title": "Gatekeeper",
      "desc": "Green Belt complete — permissions",
      "cond": {
        "type": "belt",
        "n": 4
      }
    },
    {
      "icon": "💀",
      "title": "PID Tamer",
      "desc": "Blue Belt complete — processes",
      "cond": {
        "type": "belt",
        "n": 5
      }
    },
    {
      "icon": "🌐",
      "title": "Net Runner",
      "desc": "Purple Belt complete — networking",
      "cond": {
        "type": "belt",
        "n": 6
      }
    },
    {
      "icon": "🤖",
      "title": "Automator",
      "desc": "Brown Belt complete — scripting",
      "cond": {
        "type": "belt",
        "n": 7
      }
    },
    {
      "icon": "🗺️",
      "title": "Cartographer",
      "desc": "Red Belt complete — system craft",
      "cond": {
        "type": "belt",
        "n": 8
      }
    },
    {
      "icon": "🏁",
      "title": "Halfway There",
      "desc": "Reached 50% of the dojo",
      "cond": {
        "type": "pct",
        "v": 50
      }
    },
    {
      "icon": "👹",
      "title": "Boss Slayer",
      "desc": "Cleared the final Black Belt trial",
      "cond": {
        "type": "mission",
        "id": "9.5"
      }
    },
    {
      "icon": "🥋",
      "title": "BLACK BELT",
      "desc": "100% — you finished the dojo",
      "cond": {
        "type": "all"
      }
    }
  ],
  "rewards": [
    {
      "belt": 2,
      "label": "Yellow Belt",
      "default": "a fancy açaí / your favorite treat 🍧"
    },
    {
      "belt": 3,
      "label": "Orange Belt",
      "default": "a guilt-free afternoon of your show 📺"
    },
    {
      "belt": 4,
      "label": "Green Belt",
      "default": "a new game or a fresh skin 🎮"
    },
    {
      "belt": 5,
      "label": "Blue Belt",
      "default": "your favorite pizza night 🍕"
    },
    {
      "belt": 6,
      "label": "Purple Belt",
      "default": "a totally free day 🏖️"
    },
    {
      "belt": 7,
      "label": "Brown Belt",
      "default": "an upgrade for your setup 🖥️"
    },
    {
      "belt": 8,
      "label": "Red Belt",
      "default": "a proper dinner out 🍜"
    },
    {
      "belt": 9,
      "label": "Black Belt",
      "default": "a black-belt celebration — you decide 🏆"
    }
  ]
};
