# AUTO-GENERATED by tools/generate.py — do not edit by hand.
# Sourced by ./check for the kata of the day and sensei fortunes.
DOJO_KATAS=$(cat <<'EOF'
Without looking anything up: create a tree of 3 folders with one command, a file in each, and list it all with `ls -R`.
Find every file in the repo modified in the last 24h (`find . -mtime -1`).
Build a pipeline that counts how many unique words a text file has.
In vim, write 5 lines, duplicate the last (`yy p`), replace a word everywhere (`:%s`) and save.
Start a `sleep` in the background, find its PID with a pipeline, and kill it without typing the number by hand.
Translate to octal and apply: a file only you can read/write, and the group can only read.
Find the 3 largest folders under your home with `du` + `sort`.
Serve a folder with `python3 -m http.server`, confirm the port with `ss -tlnp`, `curl` it, then take it down.
Write a one-liner that appends the date and time to `diary.log` every time it runs.
Find which package owns the `grep` command (`which` + your distro's package query).
Create a new alias in your shell rc, reload it with `source`, and use it.
Read the last 20 log lines of a service with `journalctl -u <service>` (on a systemd box).
Generate 100 lines of fake log and extract only the ones containing ERROR into a file.
Compress a folder with `tar -czf` and list its contents without extracting (`-tzf`).
In `man find`, discover an option you've never used and try it.
Write an `if` in a script that checks a folder exists and complains on stderr if it doesn't.
Rank your most-used commands (`history` + `awk` + `sort` + `uniq`).
Diagnose a host: find your IP, test DNS with a lookup, and grab a site's headers with `curl -I`.
Suspend a process with Ctrl+Z, list it with `jobs`, send it to the background with `bg`, bring it back with `fg`.
Read a permission string like `-rwxr-x---` out loud, then write its octal from memory.
EOF
)
DOJO_FORTUNES=$(cat <<'EOF'
Sensei also once ran rm -rf in the wrong directory. Once.
A typo is just the shell teaching you humility.
The manual was written for you. Nobody reads it — that's your advantage.
Ctrl+C ends suffering. Ctrl+D ends sessions. Coffee ends neither.
Tab completion has prevented more disasters than any backup ever restored.
A pipe a day keeps the spreadsheet away.
Real senseis test in production. Wise senseis have backups. Be wise.
grep, and you shall find.
Yesterday you copied commands. Today you type them. Tomorrow you write them.
chmod 777 solves everything, said the intern, once.
The penguin believes in you. The penguin has seen your shell history. It still believes.
Slow is smooth, smooth is fast. sudo is neither — handle with care.
You are one man page away from looking like a wizard.
Every expert was once someone who didn't quit at 'Permission denied'.
The best time to learn vim was 10 years ago. The second best is side quest 10.1.
Somewhere, a server is quietly grateful you're learning this properly.
Exit code 0 is the shell's way of bowing back.
Errors are not failures. Errors are reps.
EOF
)
