# AUTO-GENERATED by tools/generate.py — do not edit by hand.
# Sourced by ./check for the --hint command.
DOJO_HINTS=$(cat <<'EOF'
1.1	If `hello.txt` has the wrong text, just run the echo command again — `>` overwrites.
1.1	Quotes matter: `echo "Hello, Tux!"` keeps the exclamation mark safe from the shell.
1.2	`ls -aR maze` sweeps the whole maze in one shot — corridors, shelves, everything.
1.2	`treasure_dir` wants just the directory's name (like `cellar`), not the whole path.
1.2	You can create answers.md with echo: `echo "treasure_dir=..." > answers.md` then `echo "reveal_flag=..." >> answers.md`.
1.3	One-liner for the dirs: `mkdir -p base-camp/{bin,logs/archive,notes}`.
1.3	One-liner for the files: `touch base-camp/notes/{ideas,todo}.txt`.
1.4	The signal code looks like `word-word-number`. Copy it exactly.
1.4	`wc -l logbook.txt` prints the count and the filename; the number is what you want.
1.5	`ls -aR hunt` shows every hidden file at once — the shards' paths included.
1.5	Shard order is the number in the file name, not the order you find them in.
1.5	Passphrase format: `word1 word2 word3` — no commas, no extra spaces.
2.1	Rename = `mv backup/contract.txt backup/contract-final.txt`.
2.1	If you accidentally damaged `originals/`, restore it with `git checkout -- originals` from the repo — git is your time machine in this dojo.
2.2	Preview first: `ls site/junk/tmp*.txt` — then reuse the exact same pattern with rm.
2.2	A directory with files inside needs `rm -r site/rubble` — rmdir will refuse.
2.3	Preview any pattern with `echo inbox/*.jpg` before moving.
2.3	The final sweep is just `mv inbox/* sorted/other/` — by then only non-matched files remain.
2.4	`wc -l conf-files.txt` tells you if you caught all 4.
2.4	`empty_file` wants only the name, like `something.dat` — not the full path.
2.5	Count before you fill the report: `find organized/images -type f | wc -l`.
2.5	Junk deletion: `find chaos-drive -name "*.tmp" -delete` and `find chaos-drive -name "*~" -delete` (or -exec rm {} \;).
2.5	junk_deleted = tmp files + ~ files, added together.
3.1	The frequency table's first line is `COUNT WORD` — both of your answers live right there.
3.1	23 different words hide in that file. If your unique count disagrees, check you sorted first.
3.2	`grep -c` gives you failed_count and accepted_count without wc.
3.2	The attacker tried the `admin` account from one IP a suspicious number of times.
3.3	regions.txt should have exactly 4 lines — one per region.
3.3	total_machines is data rows only: `tail -n +2 fleet.csv | wc -l`.
3.4	Count with grep: `grep -c Nimbus release.md` counts LINES — use `grep -o Nimbus release.md | wc -l` to count occurrences.
3.4	Draft had capitalized 'Linux' in two places already — those were fine and stay untouched by s/linux/Linux/g.
3.5	suspect_ip = the top talker — and look WHAT it requested: `grep 'THAT_IP' access.log | head -20`.
3.5	unique_ips: `cut -d' ' -f1 access.log | sort -u | wc -l`.
3.5	verdict is free text — say what you concluded (scanning? brute force?). Any non-empty sentence passes.
4.1	secret.env shows `-rw-r-----` → user rw (6), group r (4), other none (0) → 640.
4.1	The sticky bit is the `t` at the very end of one directory's mode string.
4.1	770 = rwx (7) rwx (7) --- (0) = `rwxrwx---`.
4.2	`ls -ld group-zone` shows a directory's own mode (without -d it lists the contents).
4.2	If `./runme.sh` says 'Permission denied', the execute bit isn't set — recheck the 755.
4.3	Set the umask, THEN create the file — order matters, umask only affects future creations.
4.3	666 − 027 = 640. That's the answer for the last key.
4.3	If a file has the wrong mode, you set the umask after creating it — recreate it (or just chmod it to the target).
4.4	Fields per line: count the colons and add one — `head -1 sample/passwd` then count.
4.4	nologin users: `grep -c nologin sample/passwd`.
4.4	ops group GID is the number in the `ops:` line of sample/group.
4.5	Do the scripts with a glob: `chmod 755 app/bin/*.sh`.
4.5	`ls -ld app/data` to check the directory's own mode is 750.
4.5	'why' just needs to be a real sentence — e.g. 'A world-readable credential file is a breach waiting to happen.'
5.1	In sample/ps.txt, %MEM is column 4. The java process is the memory hog.
5.1	The zombie is the line with STAT `Z` and `<defunct>`.
5.1	init is PID 1 by universal convention.
5.2	The daemon writes its own PID to daemon.pid, so `kill $(cat daemon.pid)` always targets it.
5.2	If it won't die, you're sending TERM (which it ignores). Use `kill -9`.
5.2	`polite_signal` accepts either `15` or `TERM`; `unstoppable_signal` is `9`.
5.3	pause_key is `ctrl+z` (case/spacing lenient); resume_bg is `bg`; hup_immune is `nohup`.
5.3	If slow.log has no 'done' yet, the task is still running — wait a few seconds and re-check.
5.4	mem_available is the last number on the `Mem:` row of sample/free.txt.
5.4	The 1-minute load is the FIRST of the three load-average numbers in sample/uptime.txt.
5.4	The sample shows a 4-core box with load 5.10 — that's above 4, so overloaded=yes.
5.5	The miner is the process burning hours of CPU TIME with a pool address in its command line.
5.5	kill_command should force-kill by PID, e.g. `kill -9 6060`.
5.5	persistence is one word — what mechanism re-launches it on schedule?
5.5	compromised_user is the USER column of the miner's row (a service account, not a human).
6.1	private_ip is the `inet` line under eth0 in sample/ip-a.txt (without the /24).
6.1	loopback is always 127.0.0.1.
6.1	A /24 has 256 addresses minus 2 reserved = 254 usable hosts.
6.2	postgres in the sample binds 127.0.0.1 — that's the safe, local-only address.
6.2	redis (port 6379) is bound to 0.0.0.0 in the sample — that's the risky exposure.
6.2	Port 443 is served by nginx in the sample.
6.3	If curl says 'connection refused', the server isn't up — re-run the python3 http.server line.
6.3	code_ok=200, code_missing=404. A permanent redirect is 301 (temporary is 302).
6.3	Free the port when done so it doesn't linger: `kill %1` stops a backgrounded job.
6.4	`-N ""` sets an empty passphrase so the lab key generates without prompting.
6.4	The .pub file starts with `ssh-ed25519 ` — that's how the checker confirms the type.
6.4	never_commit is the word `private`; ssh_dir_mode is `700`.
6.5	The backdoor port is the odd high one in ss-dump with `nc` next to it.
6.5	gateway comes from the `default via X.X.X.X` line; dns_server from `nameserver` in resolv.conf.
6.5	hijacked_domain is the domain on the suspicious third line of the hosts file.
6.5	redirect_status is the number on the `HTTP/1.1 ...` line of curl-verbose.txt.
7.1	`[ -n "$1" ]` is true when the first argument is non-empty. Quote $1 to survive spaces.
7.1	If './greet.sh' says permission denied, you forgot `chmod +x greet.sh`.
7.1	The checker runs `./greet.sh Tux` and `./greet.sh` — match both outputs exactly.
7.2	Assignment has NO spaces: `a="$1"` not `a = "$1"`.
7.2	Arithmetic needs the double parens: `$(( a + b ))`.
7.2	The checker runs calc.sh with two different pairs — make sure it reads $1 and $2, not hardcoded numbers.
7.3	Order matters: test -d before -f, and both before the 'does not exist' else.
7.3	`>&2` redirects that echo to stderr. The checker verifies the usage text is NOT on stdout.
7.3	Verify exit codes: `./filecheck.sh; echo $?` should print 1 (no arg).
7.4	The `[ -e "$entry" ] || continue` guard handles the case where a glob matches nothing.
7.4	total must equal dirs + files. The checker builds a 2-dir/3-file fixture and expects 2/3/5.
7.4	The checker greps your script for a function definition and a loop keyword — keep both.
7.5	For --help, check `[ "$1" = "--help" ]` BEFORE the no-args check (well, no-args means $# -eq 0).
7.5	Validate: `[ $# -eq 0 ]` → exit 1; `[ ! -d "$1" ]` → exit 2.
7.5	Verify an archive: `tar -tzf backups/<file>.tar.gz` should list your source files.
7.5	Retention counts only .tar.gz in backups/. Run backup.sh 4+ times and confirm `ls backups | wc -l` stays 3.
8.1	list = t, extract = x, create = c. Each pairs with z (gzip) and f (file).
8.1	Verify your new archive: `tar -tzf shipment.tar.gz` should list shipment/manifest.txt and friends.
8.2	`VAR=value command` sets VAR just for that one command's environment — the perfect demo.
8.2	Children get a COPY, so they can't change the parent → the answer is `no`.
8.2	The interactive-shell dotfile is `.bashrc`.
8.3	'every 15 minutes' is `*/15` in the minute field, `*` everywhere else.
8.3	Monday is day-of-week 1; 18:30 is minute 30, hour 18.
8.3	field_order: the fields start minute then hour. cron_env_gotcha: the classic culprit is PATH.
8.4	`command -v pm` is the portable 'is this installed?' test.
8.4	q_update is `update` (refreshes the index; upgrade installs). remove_config_too is `purge`.
8.4	redhat_family accepts dnf or yum; arch_pm is pacman.
8.5	Shift from the HIGHEST number down, or you'll overwrite .2 with .1 before saving it.
8.5	`: > "$log"` recreates the active log as empty (the app would keep writing to it).
8.5	After one rotation there must be an `app.log.1` and `app.log` must exist and be empty.
8.5	The checker fills+rotates several times and asserts the count of rotated files never exceeds <keep>.
9.1	`ls -la server-room/` reveals the dot-file backdoor; its name starts with `.hidden`.
9.1	error_count: `grep -c ERROR server-room/logs/app.log`.
9.1	The FATAL line mentions the disk filling — 'disk full' is the fatal_reason.
9.1	cron_backdoor: the cron line pipes `curl ... | bash`, so the answer word is `curl`.
9.2	shell_pid can just be `$$` (the script's own PID).
9.2	date_utc: `date -u +%Y-%m-%dT%H:%M:%SZ` — the checker only checks it starts with a YYYY-MM-DD date.
9.2	For --json, printf with a template is easiest and always valid. Keep it to ONE line.
9.2	The checker greps your file for `set -euo pipefail` (or the equivalent set -e/-u/-o pipefail) — include it.
9.3	Numeric check: the `case "$2" in ''|*[!0-9]*) ... ;; esac` idiom rejects empties and non-digits.
9.3	Render with sed replacing __PORT__, then `chmod 600` the resulting app.conf.
9.3	version= comes from `cat release/VERSION` (it's 1.0.0).
9.3	For idempotency use `mkdir -p` and overwriting copies — never assume the dirs are absent.
9.4	Use the service's own `status` exit code as truth — don't reinvent the liveness check.
9.4	Each log line needs a timestamp (a date at the front) and the keyword (OK / RESTARTED).
9.4	After a RESTARTED run, `./fake-service.sh status` must exit 0 — your watchdog actually started it.
9.4	The checker stops the service, runs your watchdog, and asserts the service is alive afterward.
9.5	Per-type moves from any depth: `find gauntlet/messy-data -name '*.txt' -exec mv {} gauntlet/sorted/text/ \;` (repeat for each extension).
9.5	total_requests = `wc -l < gauntlet/logs/access.log`; unique_ips = `cut -d' ' -f1 ... | sort -u | wc -l`.
9.5	top_ip and top_ip_hits: the first line of `cut -d' ' -f1 ... | sort | uniq -c | sort -nr | head -1`.
9.5	server_errors = count of ' 500 ' lines; not_found = count of ' 404 ' lines.
9.5	i_am must be exactly `tux-sensei`. files_sorted should be 30 after you finish the sort.
10.1	Do the steps in the listed order and the result is deterministic — the checker compares the exact final scroll.
10.1	Typed a wrong command? `u` undoes it. Truly lost? `:q!` and reopen the file (restore the original with `git restore scroll.txt` if needed).
10.1	`:%s/line/step/g` is case-sensitive — capitalized words are untouched, which is exactly what you want here.
10.2	If `git commit` complains about identity, run the two `git config --global` lines first.
10.2	`git restore` is the modern spelling; `git checkout -- <file>` does the same on older git. The checker accepts either word in restore_cmd.
10.2	The commit can include other work too — the checker only looks for the `dojo:` message in your history.
10.3	exit_status: the failed unit's Process line ends with `status=NNN` — that number.
10.3	root_cause: the journal's last lines name the command that was not found.
10.3	The runbook is prose + commands — the checker greps for the three commands and the first_step key.
EOF
)
DOJO_TITLES=$(cat <<'EOF'
1.1	Hello, Terminal
1.2	The Hidden Treasure
1.3	The Architect
1.4	Speed Reader
1.5	BOSS — The Scavenger Hunt
2.1	Copy That
2.2	The Demolition Crew
2.3	Glob Master
2.4	The Finder
2.5	BOSS — The Great Cleanup
3.1	The Pipeline
3.2	Grep Detective
3.3	Cut, Sort, Count
3.4	Stream Surgeon
3.5	BOSS — Log Forensics
4.1	The Nine Bits
4.2	Chmod Surgeon
4.3	Masks and Defaults
4.4	Users, Groups & Sudo
4.5	BOSS — Operation Lockdown
5.1	See the Machine
5.2	The Signal Path
5.3	Jobs & Nohup
5.4	Vital Signs
5.5	BOSS — The Process Detective
6.1	Who Am I Online
6.2	Ports & Listeners
6.3	Talk HTTP
6.4	SSH & Keys
6.5	BOSS — The Port Detective
7.1	Script Zero
7.2	Variables & Substitution
7.3	Decisions
7.4	Loops & Functions
7.5	BOSS — The Backup Forge
8.1	Archive Alchemy
8.2	Environment Control
8.3	Time Lords
8.4	Package Wisdom
8.5	BOSS — The Log Rotation Engine
9.1	Incident Triage
9.2	The Sysinfo Suite
9.3	The Deployer
9.4	The Watchdog
9.5	BOSS — The Final Black Belt Trial
10.1	The Vim Gauntlet
10.2	Git Time Machine
10.3	Service Commander
EOF
)
