# AUTO-GENERATED by tools/generate.py — do not edit by hand.
# Format: belt_n|belt_slug|belt_name|mission_id|mission_slug|xp|boss|title
# Consumed by ./check and tools/lib.sh
1|01-white-belt|White Belt|1.1|01-hello-terminal|100|0|Hello, Terminal
1|01-white-belt|White Belt|1.2|02-hidden-treasure|100|0|The Hidden Treasure
1|01-white-belt|White Belt|1.3|03-the-architect|100|0|The Architect
1|01-white-belt|White Belt|1.4|04-speed-reader|100|0|Speed Reader
1|01-white-belt|White Belt|1.5|05-boss-scavenger-hunt|250|1|BOSS — The Scavenger Hunt
2|02-yellow-belt|Yellow Belt|2.1|01-copy-that|100|0|Copy That
2|02-yellow-belt|Yellow Belt|2.2|02-demolition-crew|100|0|The Demolition Crew
2|02-yellow-belt|Yellow Belt|2.3|03-glob-master|100|0|Glob Master
2|02-yellow-belt|Yellow Belt|2.4|04-the-finder|100|0|The Finder
2|02-yellow-belt|Yellow Belt|2.5|05-boss-great-cleanup|250|1|BOSS — The Great Cleanup
3|03-orange-belt|Orange Belt|3.1|01-the-pipeline|100|0|The Pipeline
3|03-orange-belt|Orange Belt|3.2|02-grep-detective|100|0|Grep Detective
3|03-orange-belt|Orange Belt|3.3|03-cut-sort-count|100|0|Cut, Sort, Count
3|03-orange-belt|Orange Belt|3.4|04-stream-surgeon|100|0|Stream Surgeon
3|03-orange-belt|Orange Belt|3.5|05-boss-log-forensics|250|1|BOSS — Log Forensics
4|04-green-belt|Green Belt|4.1|01-nine-bits|100|0|The Nine Bits
4|04-green-belt|Green Belt|4.2|02-chmod-surgeon|100|0|Chmod Surgeon
4|04-green-belt|Green Belt|4.3|03-masks-and-defaults|100|0|Masks and Defaults
4|04-green-belt|Green Belt|4.4|04-users-and-sudo|100|0|Users, Groups & Sudo
4|04-green-belt|Green Belt|4.5|05-boss-operation-lockdown|250|1|BOSS — Operation Lockdown
5|05-blue-belt|Blue Belt|5.1|01-see-the-machine|100|0|See the Machine
5|05-blue-belt|Blue Belt|5.2|02-signal-path|100|0|The Signal Path
5|05-blue-belt|Blue Belt|5.3|03-jobs-and-nohup|100|0|Jobs & Nohup
5|05-blue-belt|Blue Belt|5.4|04-vital-signs|100|0|Vital Signs
5|05-blue-belt|Blue Belt|5.5|05-boss-process-detective|250|1|BOSS — The Process Detective
6|06-purple-belt|Purple Belt|6.1|01-who-am-i-online|100|0|Who Am I Online
6|06-purple-belt|Purple Belt|6.2|02-ports-and-listeners|100|0|Ports & Listeners
6|06-purple-belt|Purple Belt|6.3|03-talk-http|100|0|Talk HTTP
6|06-purple-belt|Purple Belt|6.4|04-ssh-keys|100|0|SSH & Keys
6|06-purple-belt|Purple Belt|6.5|05-boss-port-detective|250|1|BOSS — The Port Detective
7|07-brown-belt|Brown Belt|7.1|01-script-zero|100|0|Script Zero
7|07-brown-belt|Brown Belt|7.2|02-variables-substitution|100|0|Variables & Substitution
7|07-brown-belt|Brown Belt|7.3|03-decisions|100|0|Decisions
7|07-brown-belt|Brown Belt|7.4|04-loops-functions|100|0|Loops & Functions
7|07-brown-belt|Brown Belt|7.5|05-boss-backup-forge|250|1|BOSS — The Backup Forge
8|08-red-belt|Red Belt|8.1|01-archive-alchemy|100|0|Archive Alchemy
8|08-red-belt|Red Belt|8.2|02-environment-control|100|0|Environment Control
8|08-red-belt|Red Belt|8.3|03-time-lords|100|0|Time Lords
8|08-red-belt|Red Belt|8.4|04-package-wisdom|100|0|Package Wisdom
8|08-red-belt|Red Belt|8.5|05-boss-log-rotation|250|1|BOSS — The Log Rotation Engine
9|09-black-belt|Black Belt|9.1|01-incident-triage|150|0|Incident Triage
9|09-black-belt|Black Belt|9.2|02-sysinfo-suite|150|0|The Sysinfo Suite
9|09-black-belt|Black Belt|9.3|03-the-deployer|150|0|The Deployer
9|09-black-belt|Black Belt|9.4|04-the-watchdog|150|0|The Watchdog
9|09-black-belt|Black Belt|9.5|05-final-black-belt-trial|400|1|BOSS — The Final Black Belt Trial
10|10-side-quests|Side Quests|10.1|01-vim-gauntlet|100|0|The Vim Gauntlet
10|10-side-quests|Side Quests|10.2|02-git-time-machine|100|0|Git Time Machine
10|10-side-quests|Side Quests|10.3|03-service-commander|100|0|Service Commander
